vendir:
  # For installation of CLI binaries
  host:
    # os: darwin, linux, windows
    os: "darwin"
    # arch: amd64, arm64
    arch: "amd64"
  # getLatest overrides declared versions (disable using getLatest: "")
  getLatest: ""
  versions:
    kn: 1.3.1
    kp: 0.4.2
    kubectl: 1.23.5
    tce: 0.11.0
    tce-apps-plugin: 0.6.0
    yq: 4.24.5
